### ISSUE TITLE
Object#timeout is deprecated

### ISSUE THREAD

**Issue by trip30** [solanolabs/tddium#83]
Using Ruby 2.3.0, when running tddium the output pumps out tons of 'Object#timeout is deprecated' warnings. 

```
...
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:900:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:500:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/gibson/.rvm/gems/ruby-2.3.0@trip30/gems/httpclient-2.7.0.1/lib/httpclient/session.rb:787:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
...
```

It looks like this is due to the httpclient dependency being set to 2.4.0. Updating to the new httpclient 2.7.1 should clear this up.

**Comment by semipermeable** [comment]
Thanks for reporting this.  We've had issues with dependencies on httpclient in the past, and we're working on a resolution here.  Just to confirm - have you tried this with the latest version of the [`solano` gem](https://github.com/solanolabs/solano)?
